lastpass-dmenu: move lpass status check to a spot that doesn't break it

diff --git a/.bin/lastpass-dmenu b/.bin/lastpass-dmenu
--- a/.bin/lastpass-dmenu
+++ b/.bin/lastpass-dmenu
@@ -44,10 +44,6 @@
 # by setting this environment variable:
 # export LPASS_CLIPBOARD_COMMAND="xclip -selection clipboard -in -l 1"
 
-if ! lpass status; then
-  exit 1
-fi
-
 typeit=$1
 
 IFS=$'\n'
@@ -63,6 +59,10 @@ entries=($(lpass ls --long |
 selid=$(printf '%s\n' "${entries[@]}" |
   dmenu -i -p 'LastPass: ' -l 7 |
   sed 's/^.*\[id: \([0-9]\{1,\}\)\].*$/\1/')
+if ! lpass status; then
+  echo 'Lastpass-cli returning failed status' >&2
+  exit 1
+fi
 
 if [ "$typeit" == "--typeit" ]; then
   lpass show --password ${selid} |
